import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PELSIS",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo-Pelsis.png", // Ganti dengan path favicon Anda
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/" /> {/* Link to favicon */}
        {/* You can also include additional meta tags or links here */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
